export const arenaAbi = [
  {
    type: "constructor",
    inputs: [{ name: "_relayer", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isNameTaken",
    stateMutability: "view",
    inputs: [{ name: "name", type: "string" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "createAgent",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "name", type: "string" },
      { name: "ability", type: "string" },
      { name: "flavor", type: "string" },
      { name: "attack", type: "uint8" },
      { name: "defense", type: "uint8" },
      { name: "speed", type: "uint8" },
      { name: "initialKnowledge", type: "uint32" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "train",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "factId", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "battle",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idA", type: "uint256" },
      { name: "idB", type: "uint256" },
    ],
    outputs: [
      { name: "winnerId", type: "uint256" },
      { name: "loserId", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getAgents",
    stateMutability: "view",
    inputs: [
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    outputs: [
      {
        name: "page",
        type: "tuple[]",
        components: [
          { name: "id", type: "uint256" },
          { name: "owner", type: "address" },
          { name: "name", type: "string" },
          { name: "ability", type: "string" },
          { name: "flavor", type: "string" },
          { name: "attack", type: "uint8" },
          { name: "defense", type: "uint8" },
          { name: "speed", type: "uint8" },
          { name: "wins", type: "uint32" },
          { name: "losses", type: "uint32" },
          { name: "rating", type: "uint32" },
          { name: "knowledge", type: "uint32" },
          { name: "createdAt", type: "uint64" },
          { name: "lastTrainedAt", type: "uint64" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "totalAgents",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "TRAIN_COOLDOWN",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "FACT_COUNT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "AgentCreated",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "ability", type: "string", indexed: false },
      { name: "attack", type: "uint8", indexed: false },
      { name: "defense", type: "uint8", indexed: false },
      { name: "speed", type: "uint8", indexed: false },
      { name: "knowledge", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AgentTrained",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "factId", type: "uint8", indexed: false },
      { name: "knowledge", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BattleResolved",
    inputs: [
      { name: "winnerId", type: "uint256", indexed: true },
      { name: "loserId", type: "uint256", indexed: true },
      { name: "factId", type: "uint8", indexed: false },
      { name: "decidedByKnowledge", type: "bool", indexed: false },
      { name: "winnerRoll", type: "uint256", indexed: false },
      { name: "loserRoll", type: "uint256", indexed: false },
      { name: "ratingDelta", type: "uint256", indexed: false },
      { name: "winnerRatingAfter", type: "uint32", indexed: false },
      { name: "loserRatingAfter", type: "uint32", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
] as const;
