export const bithumansAbi = [
  {
    type: "constructor",
    inputs: [{ name: "_relayer", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isNameTaken",
    stateMutability: "view",
    inputs: [{ name: "name", type: "string" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "createUser",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "name", type: "string" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "previewBalance",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [{ name: "", type: "uint32" }],
  },
  {
    type: "function",
    name: "resolveWagerMatch",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idA", type: "uint256" },
      { name: "idB", type: "uint256" },
      { name: "questionId", type: "uint8" },
      { name: "correctIndex", type: "uint8" },
      { name: "answerA", type: "uint8" },
      { name: "answerB", type: "uint8" },
      { name: "answerMsA", type: "uint32" },
      { name: "answerMsB", type: "uint32" },
    ],
    outputs: [
      { name: "winnerId", type: "uint256" },
      { name: "loserId", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "startRoyaleEntries",
    stateMutability: "nonpayable",
    inputs: [{ name: "ids", type: "uint256[]" }],
    outputs: [{ name: "potAmount", type: "uint32" }],
  },
  {
    type: "function",
    name: "resolveRoyaleRound",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idA", type: "uint256" },
      { name: "idB", type: "uint256" },
      { name: "questionId", type: "uint8" },
      { name: "correctIndex", type: "uint8" },
      { name: "answerA", type: "uint8" },
      { name: "answerB", type: "uint8" },
      { name: "answerMsA", type: "uint32" },
      { name: "answerMsB", type: "uint32" },
    ],
    outputs: [
      { name: "winnerId", type: "uint256" },
      { name: "loserId", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "payRoyaleChampion",
    stateMutability: "nonpayable",
    inputs: [
      { name: "championId", type: "uint256" },
      { name: "potAmount", type: "uint32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getUsers",
    stateMutability: "view",
    inputs: [
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    outputs: [
      {
        name: "page",
        type: "tuple[]",
        components: [
          { name: "id", type: "uint256" },
          { name: "owner", type: "address" },
          { name: "name", type: "string" },
          { name: "balance", type: "uint32" },
          { name: "wins", type: "uint32" },
          { name: "losses", type: "uint32" },
          { name: "createdAt", type: "uint64" },
          { name: "lastDripAt", type: "uint64" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "totalUsers",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "WAGER",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
  },
  {
    type: "function",
    name: "INITIAL_GRANT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
  },
  {
    type: "event",
    name: "UserCreated",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "balance", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MatchResolved",
    inputs: [
      { name: "winnerId", type: "uint256", indexed: true },
      { name: "loserId", type: "uint256", indexed: true },
      { name: "questionId", type: "uint8", indexed: false },
      { name: "decidedByAnswer", type: "bool", indexed: false },
      { name: "winnerAnswerMs", type: "uint32", indexed: false },
      { name: "loserAnswerMs", type: "uint32", indexed: false },
      { name: "wager", type: "uint32", indexed: false },
      { name: "winnerBalanceAfter", type: "uint32", indexed: false },
      { name: "loserBalanceAfter", type: "uint32", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RoyaleEntriesLocked",
    inputs: [
      { name: "userIds", type: "uint256[]", indexed: false },
      { name: "potAmount", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RoyaleRoundResolved",
    inputs: [
      { name: "winnerId", type: "uint256", indexed: true },
      { name: "loserId", type: "uint256", indexed: true },
      { name: "questionId", type: "uint8", indexed: false },
      { name: "decidedByAnswer", type: "bool", indexed: false },
      { name: "winnerAnswerMs", type: "uint32", indexed: false },
      { name: "loserAnswerMs", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RoyaleChampionPaid",
    inputs: [
      { name: "championId", type: "uint256", indexed: true },
      { name: "potAmount", type: "uint32", indexed: false },
      { name: "balanceAfter", type: "uint32", indexed: false },
    ],
  },
] as const;
